### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [SashaPonomarov/kottans-js-2016#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by SashaPonomarov** [comment]
https://github.com/SashaPonomarov/kottans-js-2016/blob/master/week01/lec1/habr.html

**Comment by mkozhukharenko** [comment]
this shouldn't be inside a nav https://github.com/SashaPonomarov/kottans-js-2016/blob/master/week01/lec1/habr.html#L51-L55

read more about a [nav](http://html5doctor.com/nav-element/) element

**Comment by mkozhukharenko** [comment]
I would not wrap that elements in a article 
https://github.com/SashaPonomarov/kottans-js-2016/blob/master/week01/lec1/habr.html#L63-L74

read more about an article [element](https://html.spec.whatwg.org/multipage/semantics.html#the-article-element) What do you think?

**Comment by mkozhukharenko** [comment]
I think a username can be a figcaption 
https://github.com/SashaPonomarov/kottans-js-2016/blob/master/week01/lec1/habr.html#L70

**Comment by mkozhukharenko** [comment]
nice markup! 👍

**Comment by SashaPonomarov** [comment]
agreed on `nav` and `figcaption`, done

Concerning author info wrapped with `article` tag: it is hard to decide definitely; my reasoning was that it could in theory be reused somewhere else, e.g. a third party page with a list of habr users and their carma. And I even remember @shvaikalesh telling us something similar. But [here](http://html5doctor.com/the-article-element/) they suggest as a test whether to use `article` tag to think if it would be appropriate in RSS feed, and in our case it probably wouldn't. So how about more ambiguous `section` (my latest commit) or even more ambiguous `div`?

Thanks for the feedback, it is really helpful!

**Comment by shvaikalesh** [comment]
user is `article`, right you are, @SashaPonomarov

**Comment by mkozhukharenko** [comment]
I must have been wrong 😸  
@SashaPonomarov it's cool that you casted doubt on that question.
